ARG BASE_IMAGE=tlog-base-ubuntu1204
FROM ${BASE_IMAGE}

COPY files/ /opt/tlog_lib/files/
COPY tests/ /opt/tlog_lib/tests/

WORKDIR /opt/tlog_lib/tests
CMD ["bats", "--formatter", "tap", "/opt/tlog_lib/tests/"]
